domain: guiziweb.github.io
title: Guiziweb
email: guiziweb@gmail.com
url: https://guiziweb.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Developpeur php / symfony
baseurl: "" # the subpath of your site, e.g. /blog

linkedin_username:  camilleislasse
malt_username:  camilleislasse

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
